version: "3"
services:
  myportfolio:
    container_name: myportfolio
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    volumes:
      - .:/myportfolio
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: mysql
    image: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mydatabase:/var/lib/mysql
    healthcheck:
      test: mariadb-admin ping -h localhost --password=$MYSQL_ROOT_PASSWORD
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  mydatabase:
