version: "3"
services:
  myportfolio:
    container_name: myportfolio
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: mysql
    image: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mydatabase:/var/lib/mysql
    healthcheck:
      test: mariadb-admin ping -h localhost --password=$MYSQL_ROOT_PASSWORD
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  nginx:
    container_name: nginx
    image: jonasal/nginx-certbot
    restart: always
    environment:
      - CERTBOT_EMAIL=darthaleguy@gmail.com
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - myportfolio

volumes:
  mydatabase:
  nginx_secrets:
